name: "Prepare Environment"

description: "Checks out the repository, installs dependencies, and prepares the build folder"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential cppcheck catch2 libgtest-dev libgmock-dev libboost-all-dev doxygen graphviz

    - name: Prepare build folder
      run: |
        mkdir -p samples/SingleProject/build
        cd samples/SingleProject/build
        cmake ..
