# This is a basic workflow to help you get started with Actions

name: Single Project CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true      # Inizializza i submodule

      # Install all dependencies needed for Single Project
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential cppcheck catch2 libgtest-dev libgmock-dev libboost-all-dev doxygen graphviz

      - name: Prepare build folder
        run: |
          mkdir samples/SingleProject/build
          cd samples/SingleProject/build
          cmake ..        

      - name: Run build command
        run: |
          cd samples/SingleProject/build
          make build

      - name: Run rebuild command
        run: |
          cd samples/SingleProject/build
          make rebuild
          
      - name: Run clean command
        run: |
          cd samples/SingleProject/build
          make clean
          
      - name: Run cppcheck command
        run: |
          cd samples/SingleProject/build
          make static-check
          
      - name: Run doxygen command
        run: |
          cd samples/SingleProject/build
          make doc
          
      - name: Run boost tests command
        run: |
          cd samples/SingleProject/build
          make clean
          make test-boost
          
      #- name: Run catch2 tests command
      #  run: |
      #    cd samples/SingleProject/build
      #    make clean
      #    make test-catch2
          
      - name: Run gtest tests command
        run: |
          cd samples/SingleProject/build
          make clean
          make test-gtest
          
      - name: Run whole tests command
        run: |
          cd samples/SingleProject/build
          make clean
          make test
          
